version: "3.1"
services:
  api:
    build: ./api
    command: npm start
    links:
      - db
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    environment:
      PORT: ${PORT}
      MYSQL_IP: ${MYSQL_IP}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASS: ${MYSQL_PASS}
      MYSQL_DB: ${MYSQL_DB}
      TZ: Asia/Bangkok
    restart: always
    ports:
      - ${PORT}:3000
    depends_on:
      - db
  db:
    build: ./database
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASS}
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASS}
      TZ: Asia/Bangkok
  phpmyadmin:
    image: phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - ${PMA_PORT}:80
